### ISSUE TITLE
Memory leak in netty implementation of DockerCmdExecFactory

### ISSUE THREAD

**Issue by vuminhkh** [docker-java/docker-java#560] opened 2016-05-01 08:39 UTC
Hello,

I'm having this kind of log in my application:

08:34:25.715 ERROR ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

It happens when I switch to netty implementation com.github.dockerjava.netty.DockerCmdExecFactoryImpl

Is it a known issue ?
Thanks,

Minh Khang VU

**Comment by marcuslinke** [comment] 2016-05-01 15:41
@vuminhkh No thats not a known issue. Would it be possible for you to set `'-Dio.netty.leakDetection.level=advanced'` as described to find the leak please?

**Comment by vuminhkh** [comment] 2016-05-01 17:46
With leak detection enabled:

17:45:53.384 ERROR ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 0
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:271)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:456)
	io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:309)
	io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:1111)
	com.github.dockerjava.netty.handler.FramedResponseStreamHandler.channelRead0(FramedResponseStreamHandler.java:48)
	com.github.dockerjava.netty.handler.FramedResponseStreamHandler.channelRead0(FramedResponseStreamHandler.java:23)
	io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233)
	io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1052)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:895)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	java.lang.Thread.run(Thread.java:745)

**Comment by vuminhkh** [comment] 2016-05-01 17:50
In com.github.dockerjava.netty.handler.HttpResponseHandler, there's also a ByteBuff 'errorBody' that seem not to be released

**Comment by vuminhkh** [comment] 2016-05-01 17:59
In com.github.dockerjava.netty.handler.FramedResponseStreamHandler , autoRelease from super class SimpleChannelInboundHandler is not set to true, might it be an issue ? Anyway with my use case for the moment the stack that I copied is the only one that I reproduced.

**Comment by marcuslinke** [comment] 2016-05-01 18:50
@vuminhkh Thanks! `FramedResponseStreamHandler` calls super constructor `protected SimpleChannelInboundHandler() {
        this(true);
    }` implicitely so `autoRelease` is set to `true`. I think the problem is with `msg.copy()` here https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/netty/handler/FramedResponseStreamHandler.java#L48.

**Comment by marcuslinke** [comment] 2016-05-01 18:58
@vuminhkh As I don't know how to reproduce this I would like to ask you if you could check out docker-java sources, remove the `copy()` operation so the line looks like the following, recompile and test against this version.

```
rawBuffer.writeBytes(msg, 0, msg.readableBytes());
```

**Comment by vuminhkh** [comment] 2016-05-01 20:23
@marcuslinke I don't see the error anymore with your fix. As It's random error, I'll continue to test for a while to be really sure. Thank you.

**Comment by marcuslinke** [comment] 2016-05-02 05:03
@vuminhkh Thanks! I will fix this in master then.

**Comment by marcuslinke** [comment] 2016-05-02 19:50
Closed via #563

**Closed by marcuslinke** 2016-05-02 19:50 UTC
Labels: bug, netty
