### ISSUE TITLE
Fails with Docker for Mac 2.5.0.1

### ISSUE THREAD

**Issue by henrik242** [docker-java/docker-java#1499] opened 2020-11-17 11:14 UTC
I get `Docker command failed: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected` after upgrading Docker for Mac to 2.5.0.1. Downgrading to 2.4.0.0 fixes the problem.

```
Caused by: javax.ws.rs.ProcessingException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
        at org.glassfish.jersey.message.internal.EntityInputStream.isEmpty(EntityInputStream.java:194)
        at org.glassfish.jersey.message.internal.InboundMessageContext.hasEntity(InboundMessageContext.java:780)
        at com.github.dockerjava.jaxrs.filter.LoggingFilter.filter(LoggingFilter.java:249)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:171)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:159)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:301)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:608)
        at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.execute(JerseyDockerHttpClient.java:297)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:75)
        at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:31)
        at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:13)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.github.dockerjava.core.command.InspectContainerCmdImpl.exec(InspectContainerCmdImpl.java:52)
        at com.github.dockerjava.api.command.InspectContainerCmd$exec.call(Unknown Source)
        at com.github.dockerjava.api.command.InspectContainerCmd$exec.call(Unknown Source)
        at com.chrisgahlert.gradledcomposeplugin.tasks.container.DcomposeContainerStopTask$_containerRunning_closure4$_closure10.doCall(DcomposeContainerStopTask.groovy:64)
        at com.chrisgahlert.gradledcomposeplugin.tasks.container.DcomposeContainerStopTask$_containerRunning_closure4$_closure10.doCall(DcomposeContainerStopTask.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.chrisgahlert.gradledcomposeplugin.tasks.AbstractDcomposeTask.ignoreDockerExceptions(AbstractDcomposeTask.groovy:123)
        at jdk.internal.reflect.GeneratedMethodAccessor2011.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.chrisgahlert.gradledcomposeplugin.tasks.AbstractDcomposeTask.ignoreDockerException(AbstractDcomposeTask.groovy:118)
        at jdk.internal.reflect.GeneratedMethodAccessor2012.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.chrisgahlert.gradledcomposeplugin.tasks.container.DcomposeContainerStopTask$_containerRunning_closure4.doCall(DcomposeContainerStopTask.groovy:63)
        at com.chrisgahlert.gradledcomposeplugin.tasks.container.DcomposeContainerStopTask$_containerRunning_closure4.doCall(DcomposeContainerStopTask.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.chrisgahlert.gradledcomposeplugin.utils.DockerExecutor.runInDockerClasspath(DockerExecutor.groovy:32)
        ... 39 more
Caused by: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
        at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:263)
        at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at org.glassfish.jersey.message.internal.EntityInputStream.isEmpty(EntityInputStream.java:165)
        ... 79 more
```
Also mentioned in https://github.com/chrisgahlert/gradle-dcompose-plugin/issues/37

**Comment by bsideup** [comment] 2020-11-17 11:17
Duplicate of https://github.com/docker-java/docker-java/issues/1496

**Closed by bsideup** 2020-11-17 11:17 UTC
