### ISSUE TITLE
Fatal exception: Error closing message content input stream

### ISSUE THREAD

**Issue by llamahunter** [docker-java/docker-java#325] opened 2015-09-16 19:57 UTC
I have a removeImages task built on gradle-docker-plugin, which uses docker-java as its low level communication library.  It appears that docker-java is having some communication issues causing gradle-docker-plugin to fail.  Note that the actual docker image is successfully removed.  The error seems spurious.  This is using docker-java 2.1.1-SNAPSHOT (due to fixing issue #322).

<pre>
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':removeImages'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:208)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:186)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:111)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
    at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:171)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: javax.ws.rs.ProcessingException: Error closing message content input stream.
    at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:159)
    at org.glassfish.jersey.message.internal.InboundMessageContext$EntityContent.close(InboundMessageContext.java:151)
    at org.glassfish.jersey.message.internal.InboundMessageContext.close(InboundMessageContext.java:909)
    at com.github.dockerjava.jaxrs.connector.ApacheConnectorClientResponse.close(ApacheConnectorClientResponse.java:45)
    at org.glassfish.jersey.client.InboundJaxrsResponse.close(InboundJaxrsResponse.java:163)
    at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:25)
    at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:10)
    at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:24)
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
    at com.github.dockerjava.core.command.RemoveImageCmdImpl.exec(RemoveImageCmdImpl.java:80)
    at com.github.dockerjava.api.command.RemoveImageCmd$exec.call(Unknown Source)
    at com.bmuschko.gradle.docker.tasks.image.DockerRemoveImage.runRemoteCommand(DockerRemoveImage.groovy:22)
    at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:48)
    at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:40)
    at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
    at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:47)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 61 more
Caused by: java.io.IOException: Bad file descriptor at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@487bc2fe; file=/run/docker.sock; connected=false; bound=false]
    at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:190)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
    at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:203)
    at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:174)
    at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:198)
    at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:287)
    at org.apache.http.impl.execchain.ResponseEntityWrapper.streamClosed(ResponseEntityWrapper.java:120)
    at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:227)
    at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
    at com.github.dockerjava.jaxrs.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:616)
    at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:157)
    ... 84 more
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Bad file descriptor
    at org.newsclub.net.unix.NativeUnixSocket.read(Native Method)
    at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:187)
    ... 95 more
</pre>

**Comment by KostyaSha** [comment] 2015-09-16 20:06
Could you localise code downto plain docker-java?

**Comment by llamahunter** [comment] 2015-09-16 20:12
Nope.  This is several layers deep, but seems pretty clearly in or below the docker-java code.  Looks like someone is unexpectedly closing the unix domain socket file descriptor.

**Comment by llamahunter** [comment] 2015-09-16 20:20
Note that this happens consistently only with a certain image.  It doesn't happen with any other images. I am not sure what is special about this image.

**Comment by marcuslinke** [comment] 2015-09-17 06:28
Strange... Maybe the image is somehow damaged? Have you tried to rebuild the image? Additionallly maybe you could check whether the delete succeeds when connecting via http/https to the docker daemon?

**Comment by marcuslinke** [comment] 2015-09-24 21:03
@llamahunter Any news on this?

**Comment by llamahunter** [comment] 2015-09-24 21:59
I was removing and rebuilding the image, but it was not helping.  I had to stop doing the :removeImages task that was calling the docker-java rmi call.  Not ideal, but now at least my build completes. I suspect that there is some error deep down in docker-java or, more likely, jersey that is trying to close already closed file descriptors, possible with a race condition only exercised by some peculiarity of this image build.

**Comment by marcuslinke** [comment] 2015-09-25 05:29
Could you publish the Dockerfile and the exact docker commands/operations that leads to this error, so I can reproduce it within a test case?

**Comment by llamahunter** [comment] 2015-09-25 05:41
Well, just tried it again, and it still happens.  Unfortunately, I will need to involve our legal department to disclose the Dockerfile. Sending off an email now.

**Comment by llamahunter** [comment] 2015-09-25 15:42
Holy smokes. I'll need to snip out and save whatever I wrote for justification to the lawyers to use again later, as they said yes.  Anyway, the Dockerfile is below.  The base image is more or less centos6 with a few things added. The build is done using gradle-docker-plugin wrapped in a custom tivo-docker-plugin.  Suffice to say, it's just using docker-java to delete the image right after it's pushed to the registry.  This works fine with other images, but does not for this one for some reason.

<pre>
FROM docker.tivo.com/tivo
MAINTAINER Richard Lee <rdlee@tivo.com>

# install java
RUN yum install -y jdk1.8.0_25

# Set java install location
ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin

USER root

# install tools
RUN yum clean all; \
    rpm --rebuilddb; \
    yum install -y curl which tar sudo openssh-server openssh-clients rsync

# work around an selinux bug in centos?
RUN yum update -y libselinux

# set hadoop version
ENV HADOOP_VERSION 2.7.1

# set hadoop install location
ENV HADOOP_PREFIX /TivoData/hadoop
# it appears some legacy scripts still use HADOOP_HOME?
ENV HADOOP_HOME $HADOOP_PREFIX

# install hadoop
RUN curl -s http://www.us.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz | tar -xz -C /TivoData
RUN ln -s hadoop-$HADOOP_VERSION $HADOOP_PREFIX

# home dirs
ENV HADOOP_COMMON_HOME $HADOOP_PREFIX
ENV HADOOP_HDFS_HOME $HADOOP_PREFIX
ENV HADOOP_YARN_HOME $HADOOP_PREFIX
ENV HADOOP_MAPRED_HOME $HADOOP_PREFIX
# conf dirs
ENV HADOOP_CONF_DIR $HADOOP_PREFIX/etc/hadoop
ENV YARN_CONF_DIR $HADOOP_CONF_DIR
# log dirs
ENV HADOOP_LOG_DIR /TivoData/log/hdfs
ENV YARN_LOG_DIR /TivoData/log/yarn
ENV HADOOP_MAPRED_LOG_DIR /TivoData/log/mapred
# pid dirs
ENV HADOOP_PID_DIR /TivoData/run/hdfs
ENV YARN_PID_DIR /TivoData/run/yarn
ENV HADOOP_MAPRED_PID_DIR /TivoData/run/mapred
# data dirs
ENV NN_DATA_DIR /TivoData/hdfs/nn
ENV SNN_DATA_DIR /TivoData/hdfs/snn
ENV DN_DATA_DIR /TivoData/hdfs/dn

# XXX HACKITUDE XXX
# Because YARN does not ship with an HTTP File System plugin, we need to
# borrow one from Samza.
# Samza is written in scala, so pull minimal runtime components
RUN curl -s http://www.scala-lang.org/files/archive/scala-2.10.4.tgz | tar -xz -C $HADOOP_YARN_HOME/share/hadoop/hdfs/lib --strip-components=2 --no-anchored scala-compiler.jar scala-library.jar
# Need a scala warpper for slf4j
RUN curl -L http://search.maven.org/remotecontent?filepath=org/clapper/grizzled-slf4j_2.10/1.0.1/grizzled-slf4j_2.10-1.0.1.jar > $HADOOP_YARN_HOME/share/hadoop/hdfs/lib/grizzled-slf4j_2.10-1.0.1.jar
# The samza supplied http yarn plugin
RUN curl -L http://search.maven.org/remotecontent?filepath=org/apache/samza/samza-yarn_2.10/0.8.0/samza-yarn_2.10-0.8.0.jar > $HADOOP_YARN_HOME/share/hadoop/hdfs/lib/samza-yarn_2.10-0.8.0.jar
# Samza core
RUN curl -L http://search.maven.org/remotecontent?filepath=org/apache/samza/samza-core_2.10/0.8.0/samza-core_2.10-0.8.0.jar > $HADOOP_YARN_HOME/share/hadoop/hdfs/lib/samza-core_2.10-0.8.0.jar

# hadoop users
RUN groupadd hadoop
RUN useradd -g hadoop yarn
RUN useradd -g hadoop hdfs
RUN useradd -g hadoop mapred

# set user directories
RUN mkdir -p $HADOOP_LOG_DIR && chown hdfs:hadoop $HADOOP_LOG_DIR
RUN mkdir -p $YARN_LOG_DIR && chown yarn:hadoop $YARN_LOG_DIR
RUN mkdir -p $HADOOP_MAPRED_LOG_DIR && chown mapred:hadoop $HADOOP_MAPRED_LOG_DIR
RUN mkdir -p $HADOOP_PID_DIR && chown hdfs:hadoop $HADOOP_PID_DIR
RUN mkdir -p $YARN_PID_DIR && chown yarn:hadoop $YARN_PID_DIR
RUN mkdir -p $HADOOP_MAPRED_PID_DIR && chown mapred:hadoop $HADOOP_MAPRED_PID_DIR
RUN mkdir -p $NN_DATA_DIR && chown hdfs:hadoop $NN_DATA_DIR
RUN mkdir -p $SNN_DATA_DIR && chown hdfs:hadoop $SNN_DATA_DIR
RUN mkdir -p $DN_DATA_DIR && chown hdfs:hadoop $DN_DATA_DIR

# XXX someone needs to format the name node, but not until tandem writes the
#     config files??  Or just the hdfs-site.xml, which has no dynconfig?
# RUN runuser hdfs -s /bin/bash -c "$HADOOP_PREFIX/bin/hdfs namenode -format"

# Rewrite hadoop config files to match install location
# XXX unclear if this is really needed?  aren't these env vars set?
#RUN sed -i "/^export JAVA_HOME/ s:.*:export JAVA_HOME=$JAVA_HOME\nexport HADOOP_PREFIX=$HADOOP_PREFIX\nexport HADOOP_HOME=$HADOOP_HOME:" $HADOOP_CONF_DIR/hadoop-env.sh
#RUN sed -i "/^export HADOOP_CONF_DIR/ s:.*:export HADOOP_CONF_DIR=$HADOOP_CONF_DIR:" $HADOOP_CONF_DIR/hadoop-env.sh

# backup hadoop config files
# XXX this seems unnecssary?
#RUN mkdir $HADOOP_PREFIX/input && cp $HADOOP_CONF_DIR/*.xml $HADOOP_PREFIX/input

# copy in new static config files
COPY conf/core-site.xml $HADOOP_CONF_DIR/core-site.xml
COPY conf/hdfs-site.xml $HADOOP_CONF_DIR/hdfs-site.xml
COPY conf/mapred-site.xml $HADOOP_CONF_DIR/mapred-site.xml
COPY conf/capacity-scheduler.xml $HADOOP_CONF_DIR/capacity-scheduler.xml

# copy in new tandem config file templates
COPY tandem/templates/yarn-site.xml.metadata /home/tivo/etc/tandem/templates/yarn-site.xml.metadata
COPY tandem/templates/yarn-site.xml.template /home/tivo/etc/tandem/templates/yarn-site.xml.template

# tandem daemon configuration is in a service specific Dockerfile
</pre>

**Comment by tjdett** [comment] 2015-10-22 04:56
I'm seeing almost exactly the same thing on image saves:

```
[ERROR] [10/22/2015 04:38:57.629] [dit4c-machineshop-akka.actor.default-dispatcher-27] [akka://dit4c-machineshop/user/$a/flow-34-4-concatMatSource-singleSource-inputStreamSource-inputStreamSource-inputStreamSource] Error closing message content input stream.
javax.ws.rs.ProcessingException: Error closing message content input stream.
        at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:159)
        at org.glassfish.jersey.message.internal.InboundMessageContext$EntityContent.close(InboundMessageContext.java:151)
        at org.glassfish.jersey.message.internal.InboundMessageContext.close(InboundMessageContext.java:909)
        at com.github.dockerjava.jaxrs.connector.ApacheConnectorClientResponse.close(ApacheConnectorClientResponse.java:45)
        at org.glassfish.jersey.client.InboundJaxrsResponse.close(InboundJaxrsResponse.java:163)
        at com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.close(WrappedResponseInputStream.java:58)
        at akka.stream.impl.io.InputStreamPublisher.postStop(InputStreamPublisher.scala:119)
        at akka.actor.Actor$class.aroundPostStop(Actor.scala:477)
        at akka.stream.impl.io.InputStreamPublisher.akka$stream$actor$ActorPublisher$$super$aroundPostStop(InputStreamPublisher.scala:32)
        at akka.stream.actor.ActorPublisher$class.aroundPostStop(ActorPublisher.scala:362)
        at akka.stream.impl.io.InputStreamPublisher.aroundPostStop(InputStreamPublisher.scala:32)
        at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
        at akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)
        at akka.actor.ActorCell.terminate(ActorCell.scala:369)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:241)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: Bad file descriptor at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@4c69e5c8; file=/tmp/docker.sock; connected=false; bound=false]
        at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:190)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:195)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:174)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:198)
        at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:287)
        at org.apache.http.impl.execchain.ResponseEntityWrapper.streamClosed(ResponseEntityWrapper.java:120)
        at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:227)
        at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
        at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
        at java.io.FilterInputStream.close(FilterInputStream.java:181)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:616)
        at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:157)
        ... 23 more
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Bad file descriptor
        at org.newsclub.net.unix.NativeUnixSocket.read(Native Method)
        at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:187)
        ... 35 more
```

This obviously results in the stream being truncated. Triggering it consistently is difficult. I am still attempting to replicate it in unit tests, but I've ruled out slow consumption of the `InputStream` as a possible cause by implementing a caching layer.

**Comment by tjdett** [comment] 2015-10-23 02:07
In the Docker debug logs, this is what I see:
```
Can't add file /var/lib/docker/tmp/docker-export-304162451/3f51961ecdfc1ece0d72abbc45571fabb191bb4372493387565a0c2e6ad0394e/layer.tar to tar: io: read/write on closed pipe
```

The `io: read/write on closed pipe` suggests to me that Docker isn't expecting a closed socket either, however either the JVM or Docker must have closed the socket.

**Comment by marcuslinke** [comment] 2015-10-23 05:30
@tjdett Thanks for your investigations. Are you able to reproduce now? If yes, couldn't you simply debug and set a break point at `AFUNIXInputStream.close()` ?

**Comment by tjdett** [comment] 2015-10-23 06:52
The time it took for this exception (precisely 2 minutes) eventually pointed me in the right direction. This error doesn't mean what it suggests.

This line of code will reproduce the message:
```java
// Export an existing image
dockerClient.saveImageCmd("busybox:latest").exec()
  .close(); // Try to close the socket without reading it to completion
```

In my case, I had an intermediate proxy in my test environment (but not in dev) with a request timeout of 2 minutes. This would trigger an input stream close before EOF and emit the error.

I suspect that this is the problem for @llamahunter too:
[Google Search: gradle task executer timeout](https://www.google.com.au/search?q=gradle%20task%20executer%20timeout)

In both cases the problem is that there's an implicit `close()` on the input stream, and the input stream won't close cleanly, which causes the exception.

The fix, IMHO, would be to wrap the `InputStream` so that premature closes either emit a useful error message or squelch the exception entirely, depending on whether `close()` is safe in this context.

**Comment by llamahunter** [comment] 2015-10-23 07:00
Ahh... excellent.  So, if I understand correctly, you think it's a long running gradle task that is eventually timing out and closing the connection to the docker daemon, causing this exception to be thrown?

**Comment by KostyaSha** [comment] 2015-10-23 11:28
If output doesn't produce anything in stdout/stderr, then you may hit ReadTimeout.

**Comment by marcuslinke** [comment] 2015-10-23 13:47
So closing this now as it seems it's not a docker-java issue then. Thanks @tjdett

**Closed by marcuslinke** 2015-10-23 13:47 UTC

**Comment by tjdett** [comment] 2015-10-25 05:49
@llamahunter more precisely, it's possible that a default timeout for Gradle tasks (2 minutes?) is killing the task prematurely, which triggers a premature close of the input stream, which then triggers an exception. ie. Cleanup triggering an exception.

Removing Docker images is normally quick, but can easily become a long-running task because of the image parent issues mentioned in the link above.

I don't think it's a read timeout, but that's possible if you're seeing variable timing in the exceptions.
