### ISSUE TITLE
Issues with Elliptic Curve (ECDSA) TLS client keys.

### ISSUE THREAD

**Issue by PMLavigne** [docker-java/docker-java#440] opened 2016-01-27 15:35 UTC
I'm encountering an error when using the Docker plugin for JetBrains' IDE's, which makes use of docker-java. The original issue is here: https://youtrack.jetbrains.com/issue/IDEA-150785

Anyway, it seems like docker-java cannot connect to the docker server if the client keys are generated using ECDSA instead of RSA. The CA that signs the keys can be ECDSA, and can sign the keys with ECDSA, but if the client's key *itself* uses ECDSA I get a very unhelpful exception and no stack trace (probably due to the plugin cutting it off rather than docker-java not generating it):
`com.github.dockerjava.api.DockerClientException: Error in SSL Configuration`

For reference, I'm using:
OSX 10.11.2 (my computer)
JDK: 1.8.0_40-release 
Ubuntu 15.10 (the server)
Docker (on server): 1.9.1, build a34a1d5
Docker (on mac): 1.9.1, build a34a1d5

I'm sorry but I don't know how to get the version number from docker-java itself since it's within the plugin.

**Comment by marcuslinke** [comment] 2016-01-28 06:23
Seems the problem is here: https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/util/CertificateUtils.java#L117-L152

Using of RSA is hardcoded yet. One problem would be to detect key algorithm at runtime. Any ideas?

Appropriate bouncycastle documentation:  http://www.bouncycastle.org/wiki/display/JA1/Elliptic+Curve+Key+Pair+Generation+and+Key+Factories#EllipticCurveKeyPairGenerationandKeyFactories-WithNamedCurves

**Comment by KostyaSha** [comment] 2016-01-28 07:01
Algo is detected with parser from bounce library.

**Comment by marcuslinke** [comment] 2016-01-28 07:17
@KostyaSha Do you have any sample code?

**Comment by KostyaSha** [comment] 2016-01-28 09:35
@marcuslinke i have my own version of utils, will try to look :)

**Comment by KostyaSha** [comment] 2016-01-30 23:39
Two ssl related issues mixed in my head. But i made integration test and script that generates ssl certs. 
@PMLavigne Could you provide any info about keys generation or some info about existed keys?

**Comment by KostyaSha** [comment] 2016-01-31 00:52
seems reproduced:
```
com.github.kostyasha.yad.docker_java.com.github.dockerjava.api.DockerClientException: Error in SSL Configuration

	at com.github.kostyasha.yad.docker_java.com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:150)
	at com.github.kostyasha.yad.docker_java.com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:130)
	at com.github.kostyasha.yad.docker_java.com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:45)
	at com.github.kostyasha.it.tests.ShortTLSKeyTest.testKey(ShortTLSKeyTest.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.github.kostyasha.yad.docker_java.com.github.dockerjava.api.DockerClientException: com.github.kostyasha.yad.docker_java.org.bouncycastle.asn1.ASN1ObjectIdentifier cannot be cast to com.github.kostyasha.yad.docker_java.org.bouncycastle.openssl.PEMKeyPair
	at com.github.kostyasha.yad.other.VariableSSLConfig.getSSLContext(VariableSSLConfig.java:62)
	at com.github.kostyasha.yad.docker_java.com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:148)
	... 33 more
Caused by: java.lang.ClassCastException: com.github.kostyasha.yad.docker_java.org.bouncycastle.asn1.ASN1ObjectIdentifier cannot be cast to com.github.kostyasha.yad.docker_java.org.bouncycastle.openssl.PEMKeyPair
	at com.github.kostyasha.yad.utils.CertUtils.loadPrivateKey(CertUtils.java:92)
	at com.github.kostyasha.yad.utils.CertUtils.loadPrivateKey(CertUtils.java:116)
	at com.github.kostyasha.yad.utils.CertUtils.createKeyStore(CertUtils.java:39)
	at com.github.kostyasha.yad.other.VariableSSLConfig.getSSLContext(VariableSSLConfig.java:53)
	... 34 more
```
note: I have custom CertUtils based on docker-java, but refactored. Will try fix.

**Comment by KostyaSha** [comment] 2016-01-31 01:50
Yes, that's a problem to identify algorithm and get right factory.

**Comment by KostyaSha** [comment] 2016-01-31 02:06
Hack with try-catch works fine. `getPrivateKeyInfo` or `getPublicKeyInfo` provides algorithm method that is numeric (OID?).
for ecdsa:
`pemKeyPair.getPrivateKeyInfo().getPrivateKeyAlgorithm().getAlgorithm()` = `1.2.840.10045.2.1`
`an RSA public key, the OID is 1.2.840.113549.1.1.1`
`pemKeyPair.getPrivateKeyInfo().getPrivateKeyAlgorithm().getParameters()` somewhere in internals `1.3.132.0.35` that is http://oid-info.com/get/1.3.132.0.35

**Comment by KostyaSha** [comment] 2016-01-31 12:19
I have some integration tests and we can made tests for all possible supported key types. But i would like to do it in 3.1.0. Atm we can note that library works fine only with RSA keys.

**Comment by PMLavigne** [comment] 2016-02-02 06:53
@KostyaSha Sorry I haven't been keeping up with this thread, I've been out of town. If you still need more info, here's some relevant bits of the x509 info:

        Signature Algorithm: ecdsa-with-SHA256
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                ASN1 OID: prime256v1

The CA has the same values for public key algorithm and signature algorithm. I can get you the openssl command I used to generate them tomorrow, if that would help, though it seems you've already reproduced it without me :)

**Comment by marcuslinke** [comment] 2016-06-09 05:22
Closed via https://github.com/docker-java/docker-java/pull/529

**Closed by marcuslinke** 2016-06-09 05:22 UTC
Labels: enhancement
