### ISSUE TITLE
what to use in place of deprecated methods ?

### ISSUE THREAD

**Issue by kameshsampath** [docker-java/docker-java#1395] opened 2020-05-17 17:30 UTC
I see the methods **withNetworkMode** and **withPortBindings** are deprecated as of version 3.2.1. What are their replacements ??

```java
CreateContainerResponse containerResponse =
				client.createContainerCmd("alpine/socat")
						.withNetworkMode("mynetwork")
						.withName(containerName)
						.withExposedPorts(exposedPort)
						.withPortSpecs(portSpec)
						.withPortBindings(portBinding)
						.withCmd("-dd", socatListen, socatConnect)
						.exec();
```

**Comment by qoobic** [comment] 2020-05-18 10:04
Similar to the issue I raised (#1393). Where methods are deprecated it would be useful to have the replacement/alternative described in the documentation.

**Comment by bsideup** [comment] 2020-05-18 10:08
Duplicate of #1281

**Closed by bsideup** 2020-05-18 10:08 UTC

**Comment by kameshsampath** [comment] 2020-05-19 11:00
@qoobic  and @bsideup  thanks for pointers but has the alternate API for `portBindings`?
