### ISSUE TITLE
listImagesCmd().withImageNameFilter("blang/latex:ubuntu") returns all local images

### ISSUE THREAD

**Issue by vmassol** [docker-java/docker-java#1531] opened 2021-01-04 12:47 UTC
Hi there,

This used to work and I've updated my Docker Desktop for Mac version to the latest, currently 3.0.3 (51017) and it's not working anymore. I'm not 100% sure this is caused by this upgrade but it could be.

I was using Docker-java 3.2.5 and I've upgraded to 3.2.7 in the hope that it would fix it but it didn't and I get all the local images listed:

<img width="1235" alt="Screenshot 2021-01-04 at 13 43 00" src="https://user-images.githubusercontent.com/628267/103536770-68c78f80-4e93-11eb-92b4-a3964dc5eb19.png">

The code that I have:

```
        DockerClient dockerClient = getDockerClient();
        List<Image> images =
            dockerClient.listImagesCmd().withImageNameFilter("blang/latex:ubuntu").exec();
```

Where `getDockerClient()` is:

```
    private DockerClient getDockerClient()
    {
        DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().build();
        DockerHttpClient httpClient = new ApacheDockerHttpClient.Builder()
            .dockerHost(config.getDockerHost())
            .sslConfig(config.getSSLConfig())
            .build();
        return DockerClientImpl.getInstance(config, httpClient);
    }
```

Any idea?

Thanks a lot

**Comment by bsideup** [comment] 2021-01-04 12:49
Duplicate of https://github.com/docker-java/docker-java/issues/1523

**Closed by bsideup** 2021-01-04 12:49 UTC

**Comment by vmassol** [comment] 2021-01-04 12:54
Thanks @bsideup for the link to the issue and the workaround. Too bad that backward-compatibility is not preserved ;)

**Comment by vmassol** [comment] 2021-01-04 12:55
> Too bad that backward-compatibility is not preserved ;)

Actually it is I guess, if I set the API version. Maybe that's my error, not setting the version. Will google to see how to do that, seems the best.

**Comment by bsideup** [comment] 2021-01-04 12:56
@vmassol glad to be helpful! Setting the API version would preserve the backward compatibility, just it is not set by default :)

See https://github.com/testcontainers/testcontainers-java/blob/0e8523db9df728a31c2b951eeee08abf7196ec6f/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L243 for an example of how to set the API version :)

**Comment by vmassol** [comment] 2021-01-04 12:59
Perfect, thanks!
