### ISSUE TITLE
Search in Custom Docker Registry 

### ISSUE THREAD

**Issue by pparthenhs** [docker-java/docker-java#1181] opened 2019-03-21 15:51 UTC
How to connect and search for a image, into custom docker registry?

First, I set the config and the client.
```
DefaultDockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
          .withRegistryUsername(username)
          .withRegistryPassword(password)
          .withRegistryUrl(registry).build();

DockerClient dockerClient = DockerClientBuilder.getInstance(config).build();
```

But when I try the following command, I retrieve all Images from officiall docker registry.
```
List<SearchItem> items = dockerClient.searchImagesCmd("my_custom_iamge").exec();
```

**Comment by emrahkaya** [comment] 2020-05-19 23:26
Looks like it'll not be implemented. Duplicate of #801

**Closed** 2020-06-19 06:49 UTC
