### ISSUE TITLE
docker-java 2.1.1 bug PrivateKeyInfo cannot be cast to PEMKeyPair

### ISSUE THREAD

**Issue by samrocketman** [docker-java/docker-java#441] opened 2016-01-28 00:07 UTC
I followed https://docs.docker.com/engine/articles/https/ which resulted in generating an RSA key for the client (x509 ASCII PEM format).  I configured the Jenkins docker to connect to the docker server via TLS client auth.  When I [run the `doTestConnection()`](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-parent-0.16.0/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L594-L623) method I get the following exception.

```
...
Caused by: com.github.dockerjava.api.DockerClientException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMKeyPair
    at com.github.dockerjava.core.LocalDirectorySSLConfig.getSSLContext(LocalDirectorySSLConfig.java:57)
    at com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:138)
    ... 61 more
Caused by: java.lang.ClassCastException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMKeyPair
    at com.github.dockerjava.core.CertificateUtils.loadPrivateKey(CertificateUtils.java:127)
    at com.github.dockerjava.core.CertificateUtils.createKeyStore(CertificateUtils.java:45)
    at com.github.dockerjava.core.LocalDirectorySSLConfig.getSSLContext(LocalDirectorySSLConfig.java:50)
    ... 62 more
```

After tracking down the source I discovered the exception is caused by [this line of `docker-java-2.1.1`](https://github.com/docker-java/docker-java/blob/docker-java-2.1.1/src/main/java/com/github/dockerjava/core/CertificateUtils.java#L127).

I discovered the solution is to convert the RSA key into a longer format:

```
openssl rsa -in key.pem -text -out key.pem
```

After conversion, the exception goes away and the connection succeeds.  I feel this is a bug in `docker-java-2.1.1`.  See jenkinsci/docker-plugin#371 for more info on how I troubleshoot the issue.

**Comment by KostyaSha** [comment] 2016-01-28 00:11
Not a docker-java issue. That's caused by multiple docker-java libraries from different plugins in your jenkins installation. I can suggest to use my plugin https://github.com/KostyaSha/yet-another-docker-plugin where i fixed this issue.

**Comment by KostyaSha** [comment] 2016-01-28 00:15
Sorry i mistaken.

**Comment by KostyaSha** [comment] 2016-01-28 00:16
Library is mostly tested on ssl certs generated by boot2docker/docker-machine. Could you compare how they are generated?

**Comment by KostyaSha** [comment] 2016-01-28 00:16
Does your generated keys works with docker-client?

**Comment by KostyaSha** [comment] 2016-01-28 00:18
Also, please verify that issue exist with the latest docker-java version and provide simple code that we will be able to use for a test case. Thanks.

**Comment by KostyaSha** [comment] 2016-01-28 12:39
@samrocketman i got some free time. I will try myself. @samrocketman JFYI yet-another-docker-plugin supports TLS credentials in UI.

**Comment by samrocketman** [comment] 2016-01-28 17:26
I'll try it out, thanks for the pointer.

**Comment by KostyaSha** [comment] 2016-01-30 20:08
@samrocketman https://docs.docker.com/engine/articles/https/#client-modes
```
Warning: These TLS commands will only generate a working set of certificates on Linux. Mac OS X comes with a version of OpenSSL that is incompatible with the certificates that Docker requires.
```

PS @samrocketman it released to main update center. I resolved/refactored different issues that i was unable to do in docker-plugin + wrote first integration tests. I plan cover reported bugs with test cases and continue development. You can of course stay with any plugin you want (you can follow links here https://github.com/KostyaSha/yet-another-docker-plugin#history to compare). I'm welcome for any questions at https://github.com/KostyaSha/yet-another-docker-plugin/issues :)

**Comment by KostyaSha** [comment] 2016-01-30 22:19
I followed docker docs and generated certs works.

**Comment by KostyaSha** [comment] 2016-01-30 22:24
Could you provide exact certs that you used for 
`docker daemon --tlsverify --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem \
  -H=0.0.0.0:2376`
and 
`docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem \
  -H=$HOST:2376 version` ?

**Comment by samrocketman** [comment] 2016-02-13 10:25
Don't use them that way.  Verify it with Jenkins.  The issue occured in Jenkins.  I had no issues using the docker client with the certs.  The problem came from the docker-java library.

**Comment by KostyaSha** [comment] 2016-02-13 10:29
I spent half day and wasn't able to reproduce it. If it jenkins issue, then please fill it against jenkins plugins. It works fine in my docker plugin. So closing.

**Closed by KostyaSha** 2016-02-13 10:29 UTC

**Comment by samrocketman** [comment] 2016-02-13 10:31
This is rather frustrating as it's actually an issue.  I thoroughly describe in the original issue jenkinsci/docker-plugin#371 how to reproduce it.

**Comment by KostyaSha** [comment] 2016-02-13 10:37
@samrocketman sure, wait for some plugin dev (if they exist today at all).

**Comment by KostyaSha** [comment] 2016-02-13 10:38
@samrocketman or if you would be able to reproduce with docker-java library + certs, then please provide certs (i really followed instructions and tried your certs, but wasn't able to reproduce except using wrong keys for wrong options).

**Comment by gilles-gosuin** [comment] 2016-03-11 12:57
I am getting exactly the same issue: my certificates and key work with both curl and the Docker client, but not with docker-java.

After digging through the code (mostly [CertificateUtils](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/util/CertificateUtils.java)) and looking at [the JavaDoc for PEMParser](https://www.bouncycastle.org/docs/pkixdocs1.4/org/bouncycastle/openssl/PEMParser.html), it really looks like docker-java is overlooking the case where the private key returned by the readObject() method is NOT a PEMKeyPair but a simple PrivateKeyInfo.

The JavaDoc is pretty clear about it:

> private keys will be returned as well formed PrivateKeyInfo objects. In the case of a private key a PEMKeyPair will normally be returned if the encoding contains both the private and public key definition.

A simple way to reproduce it would be to make sure that the key file contains only the private key and not a key pair, I guess...
