### ISSUE TITLE
Half-closed socket channels may prevent long-running commands without intermediate output from completion when the client is behind NAT

### ISSUE THREAD

**Issue by netvl** [docker-java/docker-java#723] opened 2016-10-06 10:36 UTC
We had encountered a very weird (as it seemed at first) behavior of docker-java when we were executing long-running execs in containers. We need to pass stdin to the exec and obtain its stdout and stderr, so we're using the Netty-based command factory. Usually everything works just fine, however, when the exec command takes longer than one minute to complete and does not produce output during that one minute, it actually never finishes afterwards on the client side, even though it does finish on the server, and the client never receives the eventual stdout of the exec.

After sniffing the traffic between the server and the client we found out that the reason of this behavior is that docker-java closes the socket output channel, leaving the socket in a half-closed state. The conntrack module of iptables in Linux will assign such a connection the CLOSE_WAIT state and will drop it from the connection table after a timeout, which by default is 60 seconds (see, for example, [this ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1215927)). Therefore, if the client (docker-java) is behind NAT, and the gateway with NAT uses connection tracking, which is a very common setup, long-running execs which do not write to stdout/stderr for more than the configured timeout (which by default is 60 seconds) will hang indefinitely on the client side, at least until some netty/client OS timeout kicks in.

Unfortunately, this in general cannot be mitigated by configuring the NAT server simply because they are very often out of our control. The problem was actually first observed by us when the client and the server were deployed in different regions in AWS EC2.

Is using half-closed sockets really necessary?

**Comment by marcuslinke** [comment] 2016-10-06 12:39
I think it is needed. See https://github.com/docker-java/docker-java/issues/471 for details.

**Comment by marcuslinke** [comment] 2016-10-06 16:07
@netvl Could you check if the behaviour is reproducable with docker CLI please?

**Comment by marcuslinke** [comment] 2016-11-13 12:51
Closing because of no response

**Comment by netvl** [comment] 2016-11-15 14:30
Oh, I'm sorry, I didn't get the notification.
No, when I did that through the docker CLI, it did work correctly.

**Comment by marcuslinke** [comment] 2016-11-15 14:58
Looking at the latest docker CLI sources https://github.com/docker/docker/blob/1.12.x/api/client/hijack.go#L68 `resp.CloseWrite()` is called to signal the EOF of stdin to the docker deamon. So I wonder why this works with docker CLI..

**Comment by marcuslinke** [comment] 2016-11-15 16:58
@netvl I guess you have tested with docker CLI interactively. In this case the stdin InputStream is not closed, never reaches EOF and `resp.CloseWait()` is not called. So how do you pass stdin with docker-java? Probably you put your commands into a `ByteArrayInputStream` and pass it to the command, right? Doing it this way when the stream is fully consumed the connection gets half-closed. Maybe you have to use a special InputStream implementation that doesn't signal EOF (by returning -1 from the `read()` method)?

**Comment by netvl** [comment] 2016-11-16 16:15
> I guess you have tested with docker CLI interactively

Indeed, you're right. I'll try to test again with its stdin closed.

> So how do you pass stdin with docker-java? Probably you put your commands into a ByteArrayInputStream and pass it to the ExecCmd, right?

Yep, that's correct. We use ByteArrayInputStream. However, I'm not sure about not signaling EOF - what the stream should do otherwise? The only alternative I see is blocking, which I presume is not a very good idea.

**Comment by netvl** [comment] 2016-11-16 17:03
Well, I've tried to do the following. I've created an empty container with a command which idles indefinitely:
```
$ export DOCKER_HOST=tcp://...:2375
$ docker run -d alpine sh -c 'while true; do sleep 1024d; done'
```
Then I wrote the following script to the root directory of the container:
```shell
#!/bin/sh

echo awaiting input
while read line; do echo "read $line"; done
echo beginning to sleep
sleep 120s
echo done
```

The `while read` line supposedly should read everything from the standard input. I tried launching the following commands:
```
$ docker exec -i evil_spence /long-script.sh <<< "whatever"
$ docker exec -i evil_spence /long-script.sh
<here I typed "whatever<Ctrl+D>">
```
In both of these cases the script slept for 120 seconds and finished correctly. `-t` option did not do anything.

Also I tried removing the `-i` option and also removed the stdin-reading code from the script. In this case the Docker CLI won't attach to stdin at all. And this also didn't change anything, the script still worked correctly.

I'm pretty sure that I'm behind a NAT configured with the default interval.

I'll try to check tomorrow in a setup closer to the one which depends on docker-java.

**Comment by marcuslinke** [comment] 2016-11-16 17:05
If the InputStream's `read()` method would return 0 after its been consumed it should probably work. Could you test this please?
See https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/netty/InvocationBuilder.java#L320

**Comment by marcuslinke** [comment] 2016-11-17 08:04
@netvl You could check connection state with `netstat -tn` also when you are on linux at least. You should see CLOSE_WAIT state for the related docker CLI connection.

**Comment by netvl** [comment] 2016-11-17 09:36
I see very strange things with netstat, actually. When I run `docker exec`, I can observe *two* ESTABLISHED connections in the netstat output. When I press Ctrl+D to close the input stream, only *one* of them goes to the CLOSE_WAIT state on the server side (and to the FIN_WAIT2 state on the client side). The other one remains in ESTABLISHED on both sides. When the script finishes execution (normally, of course), both connections are closed.

I'll try returning zero from the input stream (though probably not until the today's evening by my local time), but doesn't the code you linked to suggest that the stream is read until `read()` returns -1, not 0?

**Comment by marcuslinke** [comment] 2016-11-17 09:42
@netv By returning 0 instead of -1 (if the stream is fully consumed of course) one would delay the half-closing of the connection. I guess if the remote exec process terminates the connection will be closed from the server side then.

**Comment by marcuslinke** [comment] 2016-11-17 09:43
Regarding the second connection: Maybe docker CLI is monitoring docker events in parallel...

**Closed** 2016-12-09 18:39 UTC
