### ISSUE TITLE
logs stop after 10M with LogSwarmObjectCmd

### ISSUE THREAD

**Issue by ohadasulin** [docker-java/docker-java#1527] opened 2020-12-24 19:12 UTC
#1489 was closed, so I open a new issue.
code did not change from #1489.

Setting log driver to:
```   
 "log-opts": {
        "max-size": "1g",
        "max-file": "2"
    },
```
did not seem to help, although I do **not** use single file - **and** `max-size`  > 10M
Every log file is size-capped at 10M.

docker-java version :`3.2.7`
driver: `com.github.docker-java:docker-java-transport-httpclient5:3.2.7`

PLEASE,
At least give me direction where to look. I'm lost...
I don't mind issuing a pull request if needed. Just need some pointers

**Comment by bsideup** [comment] 2020-12-24 19:16
Duplicate of #1489

**Closed by bsideup** 2020-12-24 19:16 UTC
