### ISSUE TITLE
Invalid Auth config file when using credsStore

### ISSUE THREAD

**Issue by mchristiansen** [docker-java/docker-java#806] opened 2017-02-28 01:24 UTC
Using a "credsStore" configuration for auth in ~/.docker/config.json causes AuthConfigFile to fail with an IOException.

```
com.github.dockerjava.api.exception.DockerClientException: Failed to parse dockerCfgFile
	at com.github.dockerjava.core.DefaultDockerClientConfig.effectiveAuthConfig(DefaultDockerClientConfig.java:268)
	at com.github.dockerjava.core.DockerClientImpl.pullImageCmd(DockerClientImpl.java:215)
Caused by: java.io.IOException: Invalid Auth config file
	at com.github.dockerjava.core.AuthConfigFile.loadConfig(AuthConfigFile.java:146)
	at com.github.dockerjava.core.DefaultDockerClientConfig.effectiveAuthConfig(DefaultDockerClientConfig.java:266)
	... 16 more
```

After a little debugging it looks like the json parsing fails silently a little earlier in AuthConfigFile.java:

```
com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [map type; class java.util.LinkedHashMap, [simple type, class java.lang.String] -> [simple type, class com.github.dockerjava.api.model.AuthConfig]] from String value ('osxkeychain'); no single-String constructor/factory method
 at [Source: config.json; line: 4, column: 3] (through reference chain: java.util.LinkedHashMap["credsStore"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:878)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:281)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:284)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:334)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2639)
	at com.github.dockerjava.core.AuthConfigFile.loadConfig(AuthConfigFile.java:117)
	at com.github.dockerjava.core.DefaultDockerClientConfig.effectiveAuthConfig(DefaultDockerClientConfig.java:266)
	at com.github.dockerjava.core.DockerClientImpl.pullImageCmd(DockerClientImpl.java:215)
```

**Comment by ldcasillas-progreso** [comment] 2017-03-06 23:18
I am experiencing what seems to be effectively the same problem.  The issue is that the [`AuthConfigFile` class' `loadConfig` static method](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/AuthConfigFile.java#L104) expects the `~/.docker/config.json` file to look either like this (which it converts to a  `Map<String, AuthConfig>`):

```
{
    "registry1.example.com": {
        "auth": "blahblahblah",
        "email": "nobody@example.com"
    },
    "registry2.example.com": {
        "auth": "blahblahblah",
        "email": "somebody@example.com"
    }
}
```

...or like this (converted to a `Map<String, Map<String, AuthConfig>`):

```
{
    "auths": {
        "registry1.example.com": {
            "auth": "blahblahblah",
            "email": "nobody@example.com"
        },
        "registry2.example.com": {
            "auth": "blahblahblah",
            "email": "somebody@example.com"
        }
    }
}
```

...but mine looks like this, with an additional top-level key other than `auths`:

```
{
    "auths": {
        "registry1.example.com": {
            "auth": "blahblahblah",
            "email": "nobody@example.com"
        },
        "registry2.example.com": {
            "auth": "blahblahblah",
            "email": "somebody@example.com"
        }
    },
    "HttpHeaders": {
        "User-Agent": "Docker-Client/17.03.0-ce (linux)"
    }
}
```

And the Jackson `ObjectMapper` cannot interpret this JSON object to either of the types that `AuthConfigFile` tries.  And it doesn't even throw an error saying that it saw a valid JSON object that didn't meet its expectations—it just falls through to the code that reads it as the older `key = value` format.

**Comment by kshchepanovskyi** [comment] 2017-03-19 22:18
Same issue. Gradle build fails with latest version of https://github.com/bmuschko/gradle-docker-plugin and `docker-java` version `3.0.6`.

config.json:

```
{
  "auths": {
    "https://index.docker.io/v1/": {}
  },
  "credsStore": "osxkeychain"
}
```

**Comment by KostyaSha** [comment] 2017-03-28 21:30
Probably we need custon deserialization. But format was used in what docker version?

**Comment by zifik** [comment] 2017-04-20 02:02
Is this same as? https://github.com/docker-java/docker-java/issues/316

In any case, support for various valid formats of config.json needs to be supported.

**Comment by lucastheisen** [comment] 2017-06-18 15:26
This also fails with a completely empty `~/.docker/config.json`.  If i delete the file, no error, but something keeps creating an empty one (not sure what, could be Docker for Windows installer).  In any case, an empty file (or one containing `{}` should not cause a failure)...

**Comment by KostyaSha** [comment] 2017-06-29 08:47
closed via https://github.com/docker-java/docker-java/pull/868

**Closed by KostyaSha** 2017-06-29 08:47 UTC

**Comment by JLLeitschuh** [comment] 2017-06-29 20:51
Can we expect a release soon with this fix? Without the fix every build relying on the [bmuschko/gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) is broken.

**Comment by iNikem** [comment] 2017-07-03 11:21
@KostyaSha any plans on releasing 3.0.12? It seems that currently no mac user can use any tool which uses docker-java :(

**Comment by iNikem** [comment] 2017-07-03 11:27
Or sorry, in fact they can. Docker for Mac can be instructed not to use "credsStore" and then everything works :)

**Comment by kallekarlberg** [comment] 2017-07-05 07:10
@iNikem how do you disable use of credStore?

**Comment by kallekarlberg** [comment] 2017-07-05 07:22
Answering my own question:
Docker -> preferences -> general :: uncheck the checkbox "Securely store credentials ..."

**Comment by cdancy** [comment] 2017-07-05 13:29
@KostyaSha any chance you could spin a new release with this fix? This is hitting a lot of users on our (gradle-docker-plugin) end. If there is anything I can do to help speed this along you need only yell!!! :)

**Comment by KostyaSha** [comment] 2017-07-05 13:36
plan release soon, seems i solved swarm tests so probably master will be forwarded to 3.1.0 at the same time

**Comment by cdancy** [comment] 2017-07-05 13:55
Thanks @KostyaSha !

**Comment by borlander** [comment] 2017-07-11 16:42
I still can reproduce the problem with the following config.json: 
```
{
  "credsStore" : "osxkeychain"
}
```

**Comment by cooniur** [comment] 2019-01-11 21:35
The error still happens with version 3.0.14 when using `com.bmuschko.docker-remote-api` gradle plugin.

`~/.docker/config` content is 
```
{
  "stackOrchestrator" : "swarm"
}
```

Docker version is `Version 2.0.0.0-mac81 (29211)`, Engine Version: 18.09.0
`Securely store Docker logins in macOS keychain` is unchecked in Preference. 

Please advise...

**Comment by calwi** [comment] 2023-02-24 07:29
> `AuthConfigFile` class' `loadConfig` static method

What does the "blahblahblah" represent here?
