### ISSUE TITLE
Push fails with Daemon 1.10-rc1

### ISSUE THREAD

**Issue by marcust** [docker-java/docker-java#437] opened 2016-01-25 15:26 UTC
Apparently the Response to push was changed:

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "aux" (class com.github.dockerjava.api.model.PushResponseItem), not marked as ignorable (9 known properties: "stream", "error", "from", "progress", "time", "status", "errorDetail", "id", "progressDetail"])
 at [Source: com.github.dockerjava.jaxrs.util.WrappedResponseInputStream@3f8bb62d; line: 134, column: 29] (through reference chain: com.github.dockerjava.api.model.PushResponseItem["aux"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:817)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:958)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1302)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1870)
	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:44)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:62)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
```

**Comment by KostyaSha** [comment] 2016-01-25 15:28
Could you refer to API version and documentation?

**Comment by marcust** [comment] 2016-01-25 15:37
It's API v1.22, but apparently the progress response is not very well documented:
https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md

**Comment by KostyaSha** [comment] 2016-01-25 15:41
Would be cool to open upstream issue documentation request.

**Comment by llamahunter** [comment] 2016-03-16 17:09
Just hit this 'aux' bug.  I see it's merged, but the issue is not closed?

**Comment by Insomnium** [comment] 2016-03-16 17:20
Same issue

**Closed** 2016-05-01 19:22 UTC
Labels: API/1.22
