### ISSUE TITLE
periodic pull failure 

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#461] opened 2016-02-12 15:18 UTC
Pulling periodically produces null because it deserializes empty json object into class with null fields. Here is the tcp dump of flow
```

HTTP/1.1 200 OK
Content-Type: application/json
Server: Docker/1.8.2-fc22 (linux)
Date: Fri, 12 Feb 2016 15:13:26 GMT
Transfer-Encoding: chunked

4f
{"stream":"Trying to pull repository docker.io/kostyasha/jenkins-slave ... "}

43
{"status":"Pulling from kostyasha/jenkins-slave","id":"jdk-wget"}

43
{"status":"Already exists","progressDetail":{},"id":"f1b10cd84249"}
43
{"status":"Already exists","progressDetail":{},"id":"172633e38420"}
43
{"status":"Already exists","progressDetail":{},"id":"fab4b1df8eb1"}
43
{"status":"Already exists","progressDetail":{},"id":"cd8265f6bf77"}
43
{"status":"Already exists","progressDetail":{},"id":"2f4d0019b032"}
43
{"status":"Already exists","progressDetail":{},"id":"c5ed3ebafd2e"}
5e
{"status":"Digest: sha256:fc90780df68dd345db58a39900174ae98c47332aa7a33361966d432493aae825"}

59
{"status":"Status: Image is up to date for docker.io/kostyasha/jenkins-slave:jdk-wget"}

4
{}

0
```
So the last json entry is `{}`, but 
https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/async/JsonStreamProcessor.java#L39-L45
continue parsing.
According to java debugger this token is `START_OBJECT`
@marcuslinke should it be also excluded?

**Comment by KostyaSha** [comment] 2016-02-12 15:18
Probably issue in `Server: Docker/1.8.2-fc22 (linux)`, will try update dind...

**Comment by KostyaSha** [comment] 2016-02-12 15:47
1.10.1 seems works :]

**Comment by KostyaSha** [comment] 2016-02-13 21:47
`START_OBJECT` can't be excluded as it only indicates on any content. It would be cool to have ability skip empty items :(

**Comment by marcuslinke** [comment] 2016-02-14 11:57
Maybe JsonToken can be cast to JSONObject that has a .length method then...

**Comment by marcuslinke** [comment] 2016-02-14 16:38
Oops. Forget about it...

**Comment by KostyaSha** [comment] 2016-02-14 16:43
WDYM?

**Comment by marcuslinke** [comment] 2016-02-14 18:23
Just ignore my previous comments... So the only we can do is to detect `next == null` and filter it from being passed to the result callback. Do you agree?

**Comment by KostyaSha** [comment] 2016-02-14 18:27
but next isn't null, it start { object. And you can't know what will be
next without reading into object. That is done to PullItem class... Where
we can't know that everything is null :)

2016-02-14 21:23 GMT+03:00 marcuslinke <notifications@github.com>:

**Comment by KostyaSha** [comment] 2016-02-15 00:32
```
     * @return a {@link JsonNode}, if valid JSON content found; null
     *   if input has no content to bind -- note, however, that if
     *   JSON <code>null</code> token is found, it will be represented
     *   as a non-null {@link JsonNode} (one that returns <code>true</code>
     *   for {@link JsonNode#isNull()}  
  public <T extends TreeNode> T readTree(JsonParser jp)
```
check  content and then

`  public <T> T treeToValue(TreeNode n, Class<T> valueType)`
WDYT?

**Comment by KostyaSha** [comment] 2016-02-15 00:33
PS thinking on how reproduce into test case...

**Comment by marcuslinke** [comment] 2016-02-15 06:09
So it hangs at `OBJECT_MAPPER.readValue(jp, clazz);`? Sorry don't really understand what the problem is here...

**Comment by marcuslinke** [comment] 2016-02-15 06:11
or is `NullpointerException`thrown from within `OBJECT_MAPPER.readValue(jp, clazz);` call?

**Comment by KostyaSha** [comment] 2016-02-16 13:47
null is thrown from isErrorIndicated from PullResposnceItem that has all fields as nulls. Because real end happened one item before.

**Comment by KostyaSha** [comment] 2016-02-16 19:31
Or pull item should have some `isEOS()` end of stream marked that would stop next items processing.

**Comment by marcuslinke** [comment] 2016-02-19 07:41
Fixed via https://github.com/docker-java/docker-java/pull/468

**Closed by marcuslinke** 2016-02-19 07:41 UTC
Labels: bug
