### ISSUE TITLE
Unable to parse ENV statements containing $

### ISSUE THREAD

**Issue by hickeng** [docker-java/docker-java#171] opened 2015-03-12 23:10 UTC
The following structure fails with the exception below:
ENV varA valueA
ENV varB $varA/valueB

I suspect this is because the replacement text is not escaped and you need this instead:
        // handle: $VARIABLE case
        currentResourceContent = currentResourceContent.replaceAll(
            "\\$" + variable, Matcher.quoteReplacement(replacementValue));

Caused by: java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:808)
	at java.util.regex.Matcher.replaceAll(Matcher.java:906)
	at java.lang.String.replaceAll(String.java:2162)
	at com.github.dockerjava.core.dockerfile.DockerfileStatement.filterForEnvironmentVars(DockerfileStatement.java:40)
	at com.github.dockerjava.core.dockerfile.DockerfileStatement$Add.transform(DockerfileStatement.java:96)
	at com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.processAddStatement(Dockerfile.java:213)
	at com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.<init>(Dockerfile.java:206)
	at com.github.dockerjava.core.dockerfile.Dockerfile.parse(Dockerfile.java:150)
	at com.github.dockerjava.core.command.BuildImageCmdImpl.<init>(BuildImageCmdImpl.java:50)
	at com.github.dockerjava.core.DockerClientImpl.buildImageCmd(DockerClientImpl.java:272)
	at org.jenkinsci.plugins.dockerbuildstep.cmd.CreateImageCommand.execute(CreateImageCommand.java:104)
	... 10 more

**Comment by marcuslinke** [comment] 2015-03-20 20:14
@hickeng Sorry, can't reproduce it with current 1.0.1-SNAPSHOT version. What version of docker-java do you use?

**Comment by hickeng** [comment] 2015-03-20 20:31
Whichever is used by the 1.2.1 version of https://wiki.jenkins-ci.org/display/JENKINS/Docker+build+step+plugin

You would need to reference varB to trigger the problem or you'll never hit the code in filterFor...
I *think* the command I was using that trigger the problem was:
ADD $varB /tmp/mydir

My environment is under rapid flux so I can't rerun to confirm right now. I'll try to do so once I've got jenkins restored and can try the plugin once again.

**Comment by marcuslinke** [comment] 2015-03-20 20:41
Thanks for the hint. Now I'm able to reproduce. Will fix it as you suggested.

**Comment by marcuslinke** [comment] 2015-03-20 20:51
Fixed with https://github.com/docker-java/docker-java/commit/d57bed76f52d4feb69880bcbc6d26e09844bf292

**Closed by marcuslinke** 2015-03-20 20:51 UTC
