### ISSUE TITLE
Jackson MismatchedInputException on HttpResponseHandler.channelRead0

### ISSUE THREAD

**Issue by lexxy23** [docker-java/docker-java#1509] opened 2020-12-02 16:30 UTC
Hi, all,

we use Jenkins with the cloud plugin to use docker for virtual nodes. The plugin uses docker-java to "talk" to Docker. Since some hours we see a stacktrace like this in the log file of jenkins:

```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.github.dockerjava.api.model.Volume` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('/home/jenkins/.jenkins') at [Source: (byte[])"{"Id":"2625c1eaa64c3909f433d174d3fdd6b4b2f04b9b3a556c0a051c850796b0a826","Created":"2020-12-02T16:19:07.033423174Z","Path":"jenkins-agent","Args":["/bin/sh"],"State":{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":90007,"ExitCode":0,"Error":"","StartedAt":"2020-12-02T16:19:07.675995573Z","FinishedAt":"0001-01-01T00:00:00Z"},"Image":"sha256:83a941821fb1632c2df3e89faa7e958d5a68faa0352d4f6d60415b8e6f6a8ae7","ResolvConfPath":"/storage/docker/"[truncated 7726 bytes]; line: 1, column: 5411] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Mounts"]->java.util.ArrayList[0]->com.github.dockerjava.api.command.InspectContainerResponse$Mount["Destination"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1590)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1215)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1480)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:207)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:347)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4591)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3624)
        at com.github.dockerjava.netty.handler.JsonResponseCallbackHandler.channelRead0(JsonResponseCallbackHandler.java:40)
        at com.github.dockerjava.netty.handler.JsonResponseCallbackHandler.channelRead0(JsonResponseCallbackHandler.java:17)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:72)
        at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
```

I am not sure what the real issue here is.

**Comment by lexxy23** [comment] 2020-12-02 16:57
Another stacktrace:

```
Dec 02, 2020 5:54:54 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 run
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='_node', connector=DockerComputerAttachConnector{user='jenkins'}, remoteFs='/home/jenkins', instanceCap=5, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@20, dockerTemplateBase=DockerTemplateBase{image='dgrabla/jk-jnlp-slave-with-node-lts', bindPorts'='3000:3000', bindAllPorts=true, memoryLimit=4096, shmSize=1024, privileged=true, tty=false}, removeVolumes=false, stopTimeout=0, pullStrategy=PULL_LATEST, pullTimeout=300, disabled=BySystem,0 ms,59 sec,Template provisioning failed., name='NodeLTS_1'}' for cloud='docker' java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.github.dockerjava.api.model.Volume` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('/home/jenkins/.jenkins') at [Source: (byte[])"{"Id":"f43e822e0272124c07ea6b276ab01a67b4385e17811c3ab823afd67f33eaea78","Created":"2020-12-02T16:54:43.897759335Z","Path":"jenkins-agent","Args":["/bin/sh"],"State":{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":101171,"ExitCode":0,"Error":"","StartedAt":"2020-12-02T16:54:44.523982091Z","FinishedAt":"0001-01-01T00:00:00Z"},"Image":"sha256:83a941821fb1632c2df3e89faa7e958d5a68faa0352d4f6d60415b8e6f6a8ae7","ResolvConfPath":"/storage/docker"[truncated 7729 bytes]; line: 1, column: 5414] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Mounts"]->java.util.ArrayList[0]->com.github.dockerjava.api.command.InspectContainerResponse$Mount["Destination"])
        at com.google.common.base.Throwables.propagate(Throwables.java:156)
        at com.github.dockerjava.core.async.ResultCallbackTemplate.throwFirstError(ResultCallbackTemplate.java:139)
        at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:94)
        at com.github.dockerjava.netty.NettyInvocationBuilder$ResponseCallback.awaitResult(NettyInvocationBuilder.java:60)
        at com.github.dockerjava.netty.NettyInvocationBuilder.get(NettyInvocationBuilder.java:139)
        at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:31)
        at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:13)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.github.dockerjava.core.command.InspectContainerCmdImpl.exec(InspectContainerCmdImpl.java:52)
        at io.jenkins.docker.connector.DockerComputerConnector.createLauncher(DockerComputerConnector.java:133)
        at com.nirima.jenkins.plugins.docker.DockerTemplate.doProvisionNode(DockerTemplate.java:731)
        at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:676)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:375)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.github.dockerjava.api.model.Volume` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('/home/jenkins/.jenkins') at [Source: (byte[])"{"Id":"f43e822e0272124c07ea6b276ab01a67b4385e17811c3ab823afd67f33eaea78","Created":"2020-12-02T16:54:43.897759335Z","Path":"jenkins-agent","Args":["/bin/sh"],"State":{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":101171,"ExitCode":0,"Error":"","StartedAt":"2020-12-02T16:54:44.523982091Z","FinishedAt":"0001-01-01T00:00:00Z"},"Image":"sha256:83a941821fb1632c2df3e89faa7e958d5a68faa0352d4f6d60415b8e6f6a8ae7","ResolvConfPath":"/storage/docker"[truncated 7729 bytes]; line: 1, column: 5414] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Mounts"]->java.util.ArrayList[0]->com.github.dockerjava.api.command.InspectContainerResponse$Mount["Destination"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1590)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1215)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
```

**Comment by nilsmahlstaedt** [comment] 2020-12-02 20:58
Hi, 
we have very comparable errors since upgrading to 3.1.5.2, resulting in a failure to start any container that have mounts configured.

When digging into the code, the model for `Mount` tries to deserialize a field `Target` when inspecting the container. Our Docker Swarm return a field called `Destination` which contains the container mountpoint of a mount.

Maybe this information helps.

Yours
Nils

**Comment by fastidias** [comment] 2020-12-04 07:16
Having the same Problem. Downgrading Jackson2 API to v 2.11.3 and it works again.

**Comment by JuniorCtba** [comment] 2020-12-08 20:04
I am also having this issue, this is any workaround about that?

**Comment by kleini** [comment] 2020-12-08 20:31
> I am also having this issue, this is any workaround about that?

downgrade FasterXML Jackson to 2.11.3.

**Comment by jemacchi** [comment] 2020-12-10 22:57
I can confirm it too: downgrade to [Jackson-API 2.11.3 ](https://updates.jenkins.io/download/plugins/jackson2-api/2.11.3/jackson2-api.hpi) worked for me (otherwise, none of agents worked)

**Comment by wumpz** [comment] 2020-12-14 14:32
With the latest updates of Jenkins and Plugins, there is a JUnit Plugin 1.47, that directly refers to this actualized Jackson - API. This one needs to be downgraded since a lot of Jenkins depends on this.

**Comment by mjeco** [comment] 2020-12-14 18:31
@jemacchi  @wumpz Reverting those two plugins fixed the issues for me. Thanks

**Comment by pjdarton** [comment] 2020-12-15 11:08
Hey folks, I've [hit a similar issue](https://github.com/jenkinsci/docker-plugin/issues/821#issuecomment-744950178) too, and FYI `@cowtowncoder` believes this is a consequence of https://github.com/FasterXML/jackson-databind/issues/2962 , which is [fixed](https://github.com/FasterXML/jackson-databind/commit/093cdcb5ce128beb6975f9cbc050ab77c4e1eebb) in Jackson 2.12.1, which should be out in a few weeks.

I expect that, if anyone finds that reverting to Jackson 2.11.3 isn't an option for them because they need >=2.12, then they may be able to use the as-yet-unreleased [Jackon 2.12.1-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-databind/2.12.1-SNAPSHOT/) build in the interim.

**Comment by pjdarton** [comment] 2021-01-14 13:48
The Jenkins jackson-api plugin version 2.12.1 has been released officially.
This affected the docker-plugin too, and folks are reporting that using upgrading to the new jackson-api plugin fixes everything for them, so it should fix this issue too.

@lexxy23 I'd suggest you try upgrading the jackson-api plugin to 2.12.1 and, if that works, you can then close this issue.

**Comment by JewelPengin** [comment] 2021-01-31 20:27
> The Jenkins jackson-api plugin version 2.12.1 has been released officially.
> This affected the docker-plugin too, and folks are reporting that using upgrading to the new jackson-api plugin fixes everything for them, so it should fix this issue too.
> 
> @lexxy23 I'd suggest you try upgrading the jackson-api plugin to 2.12.1 and, if that works, you can then close this issue.

Had this same issue with 2.12.0 - upgraded to 2.12.1 and the problem went away!

**Closed** 2021-04-12 06:40 UTC
