### ISSUE TITLE
Unable to mount local directory in Windows

### ISSUE THREAD

**Issue by m1ngyuan** [docker-java/docker-java#1490] opened 2020-11-12 05:50 UTC
Version used:

    <dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>testcontainers</artifactId>
    <version>1.15.0</version>
    </dependency>

git repo: https://github.com/m1ngyuan/docker-mount

Reproduce program code：

    @SpringBootTest
    class DemoApplicationTests {

    GenericContainer genericContainer = new GenericContainer(DockerImageName.parse("alpine:latest"));
    @Test
    void contextLoads() {
        genericContainer.withFileSystemBind("temp","/tmp", BindMode.READ_WRITE);
        genericContainer.start();
    }

    }

When I attempt to run the test, I get the following exception:

    Caused by: java.lang.IllegalArgumentException: Error parsing Bind 'D:/IdeaProjects/docker-mount/temp/:/tmp:rw'
	at com.github.dockerjava.api.model.Bind.parse(Bind.java:134)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)

**Comment by bsideup** [comment] 2020-11-12 14:43
Duplicate of #1462

**Closed by bsideup** 2020-11-12 14:43 UTC
