### ISSUE TITLE
[feature] Support for server v1.12 / api v1.24

### ISSUE THREAD

**Issue by borlander** [docker-java/docker-java#617] opened 2016-06-27 12:41 UTC
Docker plugin for IntelliJ IDEs (https://plugins.jetbrains.com/plugin/7724) uses docker-java libraries for communication with docker remote API. 

We are now receiving a lot of requests to support the new features available in server v1.12 (and remote API v1.24) and would like to understand what are your plans to support these versions.

**Comment by KostyaSha** [comment] 2016-06-27 12:47
Feel free to PR features with test cases.

**Comment by maccesch** [comment] 2016-06-27 15:27
+1

**Comment by mark-anders** [comment] 2016-06-27 16:01
+1

**Comment by KostyaSha** [comment] 2016-06-27 16:03
Guys, please place +1 in emotion and `subscribe` if you want to get notifications about updates. Thanks.

**Comment by jiridudekusy** [comment] 2016-06-28 08:39
+1

**Comment by sevikkk** [comment] 2016-06-28 10:20
Really we need bugfix for HostConfig first, and features as second goal.

Now IntelliJ is plain broken with Docker for Mac beta16, as HostConfig on start is an error now, instead of warning.

**Comment by KostyaSha** [comment] 2016-06-28 10:52
You still HAS ability to specify API version and it will continue working on existed feature set.
@borlander are you IDEA developer? Do you have some settings place?

**Comment by KostyaSha** [comment] 2016-06-28 10:53
For docker-beta please follow references from  #537 to netty issues to have native socket connection.

**Comment by borlander** [comment] 2016-06-28 10:53
@KostyaSha Yes, we know how to specify API version and for me this is out of scope of this request

**Comment by sevikkk** [comment] 2016-06-28 10:57
With docker-for mac - it's separate issue from native connection - even with TCP port-forward it does not work, because of HostConfig issue.

**Comment by borlander** [comment] 2016-06-28 11:00
@sevikkk https://youtrack.jetbrains.com/issue/IDEA-157736 will be fixed in the next plugin version. 
No changes in the docker-java library is required for this one, so please lets discuss this issue in IntelliJ youtrack.

**Comment by KostyaSha** [comment] 2016-06-28 16:10
Some thoughts here #619

**Comment by orzeh** [comment] 2016-07-07 11:02
@KostyaSha Maybe I'm wrong but to fix `HostConfig` issue is just to change `command` to `null` in  [jaxrs/StartContainerCmdExec](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/jaxrs/StartContainerCmdExec.java#L29) and [netty/exec/StartContainerCmdExec](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/netty/exec/StartContainerCmdExec.java#L26)?

**Comment by ceagan** [comment] 2016-07-11 22:14
I'm running Docker for Windows 1.12.0-rc3-beta18 (build: 5226). I'm having trouble with the API version specification as the solution to this problem and I don't think that I can use the UNIX socket solution because this is on Windows.

If I specify API version 1.11, I see this error:

> client version 1.11 is too old. Minimum supported API version is 1.12, please upgrade your client to a newer version

If I specify API version 1.12, I see this error:

> {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

From what I can tell, the Docker Daemon has pulled support for the last compatible API. Am I understanding that correctly?

I am using the docker-maven-plugin 2.11.15 from @alexec which depends on docker-java-orchestration 2.11.17 which depends on docker-java 3.0.0.

**Comment by KostyaSha** [comment] 2016-07-11 22:41
API version != docker version.
https://docs.docker.com/engine/reference/api/docker_remote_api/
set it to 1.23

**Comment by ceagan** [comment] 2016-07-12 15:46
This may be the wrong forum for this particular issue, but I think that since the code works with the Virtual Box version of Docker on Windows, that this might be an issue in docker-java.

I tried the setting you suggested and debugged the docker-maven-plugin to see what was happening. It turned out that I also had to set the `versionAutoDetect` property to `false` in order for this setting to have an effect. I then tried it with this configuration.

```
    <configuration>
        <host>tcp://localhost:2375</host>
        <version>1.23</version>
        <versionAutoDetect>false</versionAutoDetect>
    </configuration>
```

In debugging the code, this does appear to properly set the API version to 1.23, but results in a different error message. It seems like the API is returning an unexpected response.

> [ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.11.15:start (default) on project test: com.alexecollins.docker.orchestration.OrchestrationException: com.github.dockerjava.api.exception.InternalServerErrorException: EOF -> [Help 1]

For reference, when the `version` is set to `1.24`, the following error appears.

> [ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.11.15:start (default) on project test: com.alexecollins.docker.orchestration.OrchestrationException: com.github.dockerjava.api.exception.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"} -> [Help 1]

**Comment by KostyaSha** [comment] 2016-07-12 18:07
> [ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.11.15:start (default) on project test: com.alexecollins.docker.orchestration.OrchestrationException: com.github.dockerjava.api.exception.InternalServerErrorException: EOF

#615

**Comment by alexec** [comment] 2016-07-12 20:11
Does this looks like a duplicate of issue #238?

**Comment by KostyaSha** [comment] 2016-07-12 20:13
No

**Comment by alexec** [comment] 2016-07-12 20:39
Hi, 

You're correct, got my wires crossed.

I can see this is an issue for a number of the project clients. It's great to hear a project as large as IntelliJ is using it! I've some spare time at the moment, so I can afford to look into.

Does the API need to be backwards compatible? Could we say that from a certain version, you must be using a later version of the API?

Alex

**Comment by KostyaSha** [comment] 2016-07-12 20:42
@alexec atm we need fix integration tests. Like i said one of the variant could be just move models to new model and limit daemon versions, but then test and docs should be updated.
If you want to help try reproduce unstable ITs that failed on travis.

**Comment by alexec** [comment] 2016-07-12 20:43
Sure. What tests need fixing? I can probably find a few hours to sort them out.

**Comment by yamalight** [comment] 2016-07-22 09:52
@KostyaSha I feel like that's the best place to ask - are you planning to add new [services](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/3-8-services) API for API v1.24?

**Comment by KostyaSha** [comment] 2016-07-22 09:53
Of course feel free to provide PR _with_ test cases.

**Comment by yamalight** [comment] 2016-07-22 09:54
@KostyaSha thanks for quick reply! then I'll start coding 👍

**Comment by ceagan** [comment] 2016-08-02 20:04
It appears that the HostConfig issue is affecting DockerToolbox users now as well since Docker 1.12.0 is included in their most recent stable release.

**Comment by KostyaSha** [comment] 2016-08-02 20:27
@ceagan Use versioned API end point until docker-java update. In this case use `1.23` API version.

**Comment by lordofthejars** [comment] 2016-08-05 11:09
@KostyaSha @ceagan One question why works using `1.23` and Docker 1.12. 
But if I do a `dockerClient.versionCmd().exec().getApiVersion()` it returns a `1.24`. Then I choose `1.24` as `apiVersion` but then the BadRequest exception is thrown? Something we could help?

**Comment by KostyaSha** [comment] 2016-08-05 11:18
@lordofthejars could PR test case?

**Comment by lordofthejars** [comment] 2016-08-05 11:19
Sure, thanks

**Comment by lordofthejars** [comment] 2016-08-05 13:48
Using Docker 1.12 which contains Docker Remote API 1.24.

Gist with failure: https://gist.github.com/lordofthejars/16589d26cc39c8604fbb7aabe9bce2ff

Exception:

```
com.github.dockerjava.api.exception.ConflictException: {"message":"Conflict. The name \"/busybox\" is already in use by container afdd166d0f83ed26175e1a7165f33f7a3c152307c28a547eed6b9dffeb0ae036. You have to remove (or rename) that container to be able to reuse that name."}


	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:51)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilter
```

**Comment by Fabryprog** [comment] 2016-09-09 14:38
+1

**Comment by KostyaSha** [comment] 2016-09-09 14:47
> com.github.dockerjava.api.exception.ConflictException: {"message":"Conflict. The name \"/busybox\" is already in use by container afdd166d0f83ed26175e1a7165f33f7a3c152307c28a547eed6b9dffeb0ae036. You have to remove (or rename) that container to be able to reuse that name."}

That's not library issue. Please read error message.

**Comment by lordofthejars** [comment] 2016-09-09 14:58
It is already fixed, but probably wrong copy paste, see my message just before that says about bad request exception

**Comment by kletkeman** [comment] 2016-09-14 22:04
I made the TRAGIC mistake of upgrading docker ... and now I get the HostConfig error and cannot launch deployed chaincode in a Hyperledger fabric. Any ETA on a fix? Need 1.12.2 *badly* ...

**Comment by KostyaSha** [comment] 2016-09-14 22:06
@kletkeman first of all it was only JERSEY issue, secondary it was fixed. What docker-java version do you use?

**Comment by kletkeman** [comment] 2016-09-14 22:09
@KostyaSha I just slammed into this today ... I'm a user of docker without knowing much about its ins and outs. How do I find the docker-java version, or can I just upgrade it?

**Comment by KostyaSha** [comment] 2016-09-14 22:10
@kletkeman where do you see this error? Could you fill separate issue as it already overloaded with different errors?

**Comment by kletkeman** [comment] 2016-09-14 22:14
@KostyaSha I see it on a 4 node Hyperledger fabric ... each of them fails to start a docker container for my deployed smart contract. I suspect that docker-java is involved because there is java contract technology in there, even though I don't use java for anything (golang is my preference) ...

vp0_1 | 21:57:39.806 [dockercontroller] Start -> ERRO 033 start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
vp0_1 | 21:57:39.806 [chaincode] Launch -> ERRO 034 launchAndWaitForRegister failed Error starting container: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
vp0_1 | 21:57:39.806 [consensus/pbft] execDoneSync -> INFO 035 Replica 0 finished execution 1, trying next
vp3_1 | 21:57:39.833 [dockercontroller] Start -> ERRO 027 start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
vp3_1 | 21:57:39.834 [chaincode] Launch -> ERRO 028 launchAndWaitForRegister failed Error starting container: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
vp3_1 | 21:57:39.834 [consensus/pbft] execDoneSync -> INFO 029 Replica 3 finished execution 1, trying next
vp1_1 | 21:57:39.895 [dockercontroller] Start -> ERRO 027 start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
vp1_1 | 21:57:39.895 [chaincode] Launch -> ERRO 028 launchAndWaitForRegister failed Error starting container: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
vp1_1 | 21:57:39.895 [consensus/pbft] execDoneSync -> INFO 029 Replica 1 finished execution 1, trying next
vp2_1 | 21:57:39.941 [dockercontroller] Start -> ERRO 027 start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
vp2_1 | 21:57:39.941 [chaincode] Launch -> ERRO 028 launchAndWaitForRegister failed Error starting container: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
vp2_1 | 21:57:39.942 [consensus/pbft] execDoneSync -> INFO 029 Replica 2 finished execution 1, trying next

When you say that the HostConfig container start issue was fixed, can you tell me where? I.e. what would I do to make this work? Thanks.

**Comment by KostyaSha** [comment] 2016-09-14 22:16
@kletkeman you need feel issue to project that uses docker-java.

**Comment by kletkeman** [comment] 2016-09-14 23:47
@KostyaSha a user of hyperledger mentioned to me that they tried every combination of 1.10/11/12 for docker and gave up ... they have backed off to 1.8.5 ... which is what I will do ... I look forward to a day when the new stuff functions ...

**Comment by KostyaSha** [comment] 2016-09-14 23:49
@kletkeman on github i didn't found any reference to docker-java. I can only guess that they are using old docker container control logic and that's why you have this error.

**Comment by kletkeman** [comment] 2016-09-14 23:56
@KostyaSha Thanks. Regarding docker-java ... I don't see how it is not related since you mentioned docker-java as you very first response. It is my understanding that a docker-java issue drove the loss of support for HostConfig in the first place, hence everyone has to change their code to react to that. I appreciate you pointing to the error, but that only became an error because of changes outside their control.

**Comment by KostyaSha** [comment] 2016-09-15 00:02
What control? I don't understand. Docker changed their API, not because of docker-java, because they do it every version. Docker-java got this issue because we didn't fix docker-java code ahead, etc. Docker-java is the most used library that's why google will show you such error in first results. So again, your issue not related to docker-java. 

> since you mentioned docker-java as you very first response. It is my understandi

Here people reporting issues only for projects that using docker-java. That was also expected from your report.

**Comment by borntorock** [comment] 2017-01-10 13:51
@KostyaSha Hi, I'm working with Intellij 15 and docker deployment plugin (docker v1.12.5 installed via docker machine on host system which includes api v1.24).

I'm facing the issue ```Failed to deploy 'demo-container5  Image Id: 67591570dd29': com.github.dockerjava.api.BadRequestException: {"message":"starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"} ```

Even after reading the comments of all the folks in this issue, not able to figure out the solution. Has the new api version being taken care of in the docker-java source code?

Would highly appreciate to hear back from you, on how shall I resolve this issue.

**Comment by KostyaSha** [comment] 2017-01-10 13:53
What docker-java version do you use?

**Comment by borntorock** [comment] 2017-01-10 14:00
@KostyaSha How shall I find the docker-java version? I'm not specifically installed any version. Though @kletkeman asked about this above, but there seems to be no answer.

**Comment by borntorock** [comment] 2017-01-10 14:02
Docker Integration version is 1.7.6 and IDE is using JAVA 7.

**Comment by KostyaSha** [comment] 2017-01-10 14:08
I don't know what docker-java version does they use, but i have no problems with 1.12 in https://github.com/KostyaSha/yet-another-docker-plugin so i guess they are on ancient version. 
Ask them update to latest docker-java version or provide more detailed request than "support 1.12 features".

**Closed by KostyaSha** 2017-01-10 14:08 UTC
Labels: API/1.24

**Comment by viatra2** [comment] 2017-01-10 14:15
@borntorock This should work out of the box in any plugin version compatible with IDEA 2016.x. Please upgrade your IDEA

**Comment by borlander** [comment] 2017-01-10 14:16
@borntorock This should work out of the box in any plugin version compatible with IDEA 2016.x. Please upgrade your IDEA
