### ISSUE TITLE
huge image upload

### ISSUE THREAD

**Issue by xiongxinxin** [docker-java/docker-java#1480] opened 2020-11-02 02:30 UTC
Now I hava a task that demand me upload docker-image to harbor,but this image is more than 20G.Can i get a advice or solution?

**Comment by bsideup** [comment] 2020-11-02 07:44
See `CreateImageCmd` and also `PushImageCmd`, plus https://docs.docker.com/engine/api/v1.40/

I am closing this issue as it is not a bug report / feature request. Feel free to create a new issue if you think there is a bug.

Also, consider asking your question on StackOverflow next time, to get answers from broader community.

**Closed by bsideup** 2020-11-02 07:44 UTC
