### ISSUE TITLE
How to specify mount via the SDK?

### ISSUE THREAD

**Issue by qoobic** [docker-java/docker-java#1393] opened 2020-05-15 16:21 UTC
Hello,

I need to create a volume for use by several containers. It is not clear from the examples how I should mount a named volume into a container via the SDK?

Via the CLI, I can create a named volume and mount it like this:
```
docker volume create  --name my-volume
docker -D run -d --mount type=volume,source=my-volume,destination=/tmp/hello busybox top
```

To do the same via the SDK, I can create a named volume and mount it through a bind when I create the container, ie:
```
dockerClient.createVolumeCmd().withName(volumeName).exec();

Volume destinationVolume = new Volume("/tmp/hello");
CreateContainerResponse container = dockerClient.createContainerCmd("busybox")
    .withVolumes(destinationVolume)
    .withBinds(new Bind(volumeName, destinationVolume))
    .withCmd("top")
    .exec();
```
But the `withBinds` method on `CreateContainerCmd` is marked as deprecated in version 1.39.

How should I be doing this?

**Comment by bsideup** [comment] 2020-05-18 10:08
Duplicate of #1281

**Closed by bsideup** 2020-05-18 10:08 UTC

**Comment by qoobic** [comment] 2020-05-18 10:19
Specifically and for information only, the answer to my question is therefore to replace this:
```
.withBinds(new Bind(volumeName, destinationVolume))
```
With this:
```
.withHostConfig(HostConfig.newHostConfig().withBinds(new Bind(volumeName, destinationVolume)))
```
