### ISSUE TITLE
Hanging in AwaitCompletion of ExecStartResultCallback # JAXRS

### ISSUE THREAD

**Issue by gerdogdu** [docker-java/docker-java#481] opened 2016-02-26 00:27 UTC
ExecStartResultCallback resultCallBack = new ExecStartResultCallback(stdOut, stdError);
getDockerClient().execStartCmd(containerId).withExecId(executionId).withDetach(false).withTty(false)
 .exec(resultCallBack);

resultCallBack.awaitCompletion(); --> This is never returns

It hangs in  int read = inputStream.read(rawBuffer); of FrameReader

**Comment by marcuslinke** [comment] 2016-02-26 07:37
@gerdogdu JAX-RS version of ExecStart doesn't support STDIN redirection to container. This is the main reason for introducing the whole netty implementation.
I would suggest to switch to netty impl as this will supersede the JAX-RS based one with one of the next releases. Therefore I don't want invest too much in fixing JAX-RS impl. Is this an option for you?

**Comment by gerdogdu** [comment] 2016-02-26 08:49
I understand, I also tried netty but still awaitCompletion hangs. My test code as below:

`        CreateContainerResponse container = dockerClient.createContainerCmd("ubuntu").withCmd("sleep", "9999")
                .withName(containerName).exec();
        LOG.info("Created container {}", container.toString());
        assertThat(container.getId(), not(isEmptyString()));

        dockerClient.startContainerCmd(container.getId()).exec();

        ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(container.getId())
                .withAttachStdout(true).withTty(true).withCmd("bash").exec();
        dockerClient.execStartCmd(execCreateCmdResponse.getId()).withDetach(false)
                .exec(new ExecStartResultCallback(System.out, System.err)).awaitCompletion();
`

**Comment by marcuslinke** [comment] 2016-02-26 10:22
@gerdogdu Are you sure that `awaitCompletion()` hangs forever. I guess it will block for 9999 seconds only.

**Comment by gerdogdu** [comment] 2016-02-26 11:48
Sorry to ask but I want to execute bash cmd and wanted to go into root@3434422 and then within upgraded TPC session, I want to execute other commands like ls, cat etc. How could I do this?

In the above code, why awaitCompletion returns because it just runs bash cmd?

**Comment by marcuslinke** [comment] 2016-02-26 12:21
Take a look at this test case here https://github.com/docker-java/docker-java/blob/822cb327d21370a059ef7cc1aa50341d273aa0df/src/test/java/com/github/dockerjava/netty/exec/ExecStartCmdExecTest.java#L101-L122

It does what you want but calls `awaitCompletion(5, TimeUnit.SECONDS)`, so the whole operation is cancelled after 5 seconds. If you call `awaitCompletion()` you have a long running operation for interacting with the container via `stdin`. As long as the `stdin` InputStream doesn't reaches EOF the connection will be kept open.

**Comment by gerdogdu** [comment] 2016-02-26 13:30
The problem is that when I put breakpoint in run method of InvocationBuilder `                @Override
                public void run() {

                    byte[] buffer = new byte[1024];

                    int read;
                    while ((read = read(stdin, buffer)) != -1) {
                        channel.writeAndFlush(Unpooled.copiedBuffer(buffer, 0, read));
                    }

                    // we close the writing side of the socket, but keep the read side open to transfer stdout/stderr
                    channel.shutdownOutput();

                }
            }).start();

` then it shows command execution result. Otherwise, it does not produce anything

**Comment by gerdogdu** [comment] 2016-02-26 13:34
Here is the code. If I don't put breakpoint into the above method, it only shows the "ls" in Stdout. If I put breakpoint into above and step step execution, it shows ls execution result.

`ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(container.getId()).withAttachStdin(true)`
`.withAttachStdout(true).withTty(true).withCmd("bash").exec();`
`InputStream stdin = new ByteArrayInputStream("ls\n".getBytes("UTF-8"));`
`ExecStartResultCallback execStartResultCallback = new ExecStartResultCallback(System.out, System.err);`
`dockerClient.execStartCmd(execCreateCmdResponse.getId()).withDetach(false).withStdIn(stdin)
                .exec(execStartResultCallback);`
`execStartResultCallback.awaitCompletion(10,TimeUnit.SECONDS);`

**Comment by KostyaSha** [comment] 2016-02-26 13:36
Are you sure that ls will be executed with `sh`?

**Comment by marcuslinke** [comment] 2016-02-26 13:38
Could you provide the your appropriate code snippet please?

**Comment by gerdogdu** [comment] 2016-02-26 13:41
`@Test(groups` = "ignoreInCircleCi")
    `public` void execStartAttachedUbuntu() throws Exception {
        `String` containerName = "generated_" + new SecureRandom().nextInt();

        CreateContainerResponse container = dockerClient.createContainerCmd("ubuntu").withCmd("sleep", "9999")
                .withName(containerName).exec();
        LOG.info("Created container {}", container.toString());
        assertThat(container.getId(), not(isEmptyString()));

        dockerClient.startContainerCmd(container.getId()).exec();

        ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(container.getId()).withAttachStdin(true)
                .withAttachStdout(true).withTty(true).withCmd("bash").exec();
        
        InputStream stdin = new ByteArrayInputStream("ls\n".getBytes("UTF-8"));
        ExecStartResultCallback execStartResultCallback = new ExecStartResultCallback(System.out, System.err);
        dockerClient.execStartCmd(execCreateCmdResponse.getId()).withDetach(false).withStdIn(stdin)
                .exec(execStartResultCallback);
        
        execStartResultCallback.awaitCompletion(10,TimeUnit.SECONDS);
        
        
        stdin.close();        

     }
`

**Comment by marcuslinke** [comment] 2016-02-26 13:47
Just a guess but maybe the problem here is that `stdin` InputStream is EOF and therefore the connection is closed before the output of `ls` command is received from docker. Could you test with `withStdIn(System.in)` and try to do `ls` interactively please?

**Comment by KostyaSha** [comment] 2016-02-26 13:49
Or send commands into not closed stream after exec?

**Comment by gerdogdu** [comment] 2016-02-26 13:56
Yes stdin seems to work, how could we workaround this?

**Comment by marcuslinke** [comment] 2016-02-26 14:28
At the moment the only workaround would be to wait a few seconds before EOF is sent from `stdin` InputStream downstream. Maybe we have to change the API for this. 

@rtimush Any ideas?

**Comment by KostyaSha** [comment] 2016-02-26 14:29
What is the sense of using inputStream for sending single command?

**Comment by marcuslinke** [comment] 2016-02-26 15:51
@KostyaSha What do you mean?

**Comment by rtimush** [comment] 2016-02-26 18:23
It seems that the problem reproduces only if tty is enabled. I suppose it is ok — if you close tty it means that your session should be closed and there is no place to display the output.

**Comment by marcuslinke** [comment] 2016-02-26 18:28
@gerdogdu OK. Just found the reason. Please remove `.withTty(true)` from create exec command. Then it will work.

**Comment by marcuslinke** [comment] 2016-02-26 18:35
@rtimush Thanks for explanation. But that doesn't explain why it works when he sets a breakpoint as described above...

**Comment by KostyaSha** [comment] 2016-02-26 18:53
Could everybody provide `docker version` infos? :)

**Comment by gerdogdu** [comment] 2016-02-26 20:12
When I remove .withTty(true) then nothing appeared in stdout. I use macosx docker version docker-machine version 0.4.1 (e2c88d6) and Docker version 1.8.1, build d12ea79

**Comment by gerdogdu** [comment] 2016-02-26 20:14
@KostyaSha I have a websocket client with HTML terminal to execute bash commands

**Comment by marcuslinke** [comment] 2016-02-26 21:30
@gerdogdu Tested the following code against docker 1.8.1 successfully here:

```
    public void execStartAttachStdinToShell() throws Exception {

        dockerClient
                .pullImageCmd("ubuntu:latest").exec(new PullImageResultCallback()).awaitCompletion();

        String containerName = "generated_" + new SecureRandom().nextInt();

        CreateContainerResponse container = dockerClient
                .createContainerCmd("ubuntu")
                .withCmd("sleep", "9999")
                .withName(containerName)
                .exec();

        LOG.info("Created container {}", container.toString());
        assertThat(container.getId(), not(isEmptyString()));

        dockerClient.startContainerCmd(container.getId()).exec();

        InputStream stdin = new ByteArrayInputStream("ls\n".getBytes());

        ByteArrayOutputStream stdout = new ByteArrayOutputStream();

        ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(container.getId())
                .withAttachStdout(true)
                .withAttachStdin(true)
                .withTty(false)
                .withCmd("/bin/sh").exec();

        dockerClient.execStartCmd(execCreateCmdResponse.getId())
                .withDetach(false)
                .withStdIn(stdin)
                .exec(new ExecStartResultCallback(stdout, System.err))
                .awaitCompletion();

        assertThat(stdout.toString(), containsString("etc\n"));
    }
```

```
Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by marcuslinke** [comment] 2016-02-26 22:36
@rtimush Let me summarize my current understanding of whats going on there: Enabling tty enables a terminal session, so when end of `stdin` stream is detected and we call `channel.shutdownOutput()` the docker deamon detects that and assumes we want to quit that session. Then it kills the tty and/or connection that is needed to pass stdout back to us. 

With disabled tty there is no terminal session that could be cancelled so stdout is passed back to us as long as the process stays alive. Do you agree?

**Comment by gerdogdu** [comment] 2016-02-27 15:45
Because I use bash and execute commands need tty enabled. With tty enabled, now it works for me. Thanks for all .

**Comment by rtimush** [comment] 2016-02-29 05:48
@marcuslinke yes, my understanding is the same

**Comment by marcuslinke** [comment] 2016-02-29 06:14
@rtimush OK. Thanks. The question that arises to me is whether we need an API change then. If tty is enabled maybe the caller needs a possibility to close the terminal session explicitely not only as a side effect of stream EOF. WDYT? Would it be needed?

**Comment by marcuslinke** [comment] 2016-02-29 06:15
@gerdogdu How you solved the "stream EOF -> disconnect" problem when tty is enabled?

**Comment by gerdogdu** [comment] 2016-02-29 07:54
@marcuslinke when user disconnects from terminal, I close inputstream to close the channel.

**Comment by marcuslinke** [comment] 2016-02-29 08:05
@gerdogdu So if I understand you right your use case is an interactive user session then, right?

@all But what if someone needs non-interactive execution of commands with demand for receiving terminal control characters? Would that be a possible use case? And wouldn't that mean an API change for handing a `closeChannel()` like functionality out to the caller?

**Comment by gerdogdu** [comment] 2016-02-29 08:14
@marcuslinke  I think it is a good idea to provide such API

**Comment by rtimush** [comment] 2016-02-29 08:59
@marcuslinke Such API may be useful if we can do something other than sending bytes to stream and closing the channel. My current understanding is that we don't have other controls.

I believe that in TTY mode end of stream can be sent without closing the channel, because it can be done more than once, but I don't know how it is done.

**Comment by marcuslinke** [comment] 2016-02-29 09:16
@rtimush So you believe that netty simply doesn't provide a proper API to send EOF without (half) closing the channel?

**Comment by rtimush** [comment] 2016-02-29 12:55
I think this is the only option available in TCP, so netty just cannot provide anything else.

**Comment by marcuslinke** [comment] 2016-02-29 13:14
OK. So I just misunderstood you, sorry.

**Closed** 2016-02-29 14:39 UTC
