### ISSUE TITLE
Capability enum does not count with unknown capabilities

### ISSUE THREAD

**Issue by psakar** [docker-java/docker-java#1500] opened 2020-11-20 11:08 UTC
When running testcontainers with podman I'm getting following exception

Cannot deserialize value of type `com.github.dockerjava.api.model.Capability`

at [Source: (org.testcontainers.shaded.okio.RealBufferedSource$1); line: 1, column: 1683] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["HostConfig"]->com.github.dockerjava.api.model.HostConfig["CapDrop"]->java.lang.Object[][0])
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.get(OkHttpInvocationBuilder.java:92)
	at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:31)

Is it possible to either ignore uknown capabilities or change enum to string ?

**Comment by psakar** [comment] 2020-11-20 11:09
Full error description is 

```
Caused by: java.lang.RuntimeException: org.testcontainers.shaded.com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.github.dockerjava.api.model.Capability` from String "CAP_MKNOD": not one of the values accepted for Enum class: [ALL, SYS_BOOT, DAC_OVERRIDE, NET_RAW, BLOCK_SUSPEND, FOWNER, IPC_LOCK, IPC_OWNER, SYS_PACCT, NET_BIND_SERVICE, WAKE_ALARM, FSETID, DAC_READ_SEARCH, SYS_CHROOT, SYS_RAWIO, SYS_ADMIN, KILL, MAC_ADMIN, SYS_RESOURCE, CHOWN, SETPCAP, SYS_PTRACE, NET_ADMIN, SETFCAP, SYS_NICE, LINUX_IMMUTABLE, AUDIT_CONTROL, LEASE, AUDIT_WRITE, SYS_MODULE, MKNOD, SYSLOG, MAC_OVERRIDE, SYS_TIME, SETGID, SETUID, SYS_TTY_CONFIG, NET_BROADCAST]
```

**Comment by psakar** [comment] 2020-11-20 11:11
I can try to provide PR given I would know which direction to go ...

**Comment by bsideup** [comment] 2020-11-20 11:23
Duplicate of #1488

**Closed by bsideup** 2020-11-20 11:23 UTC
